<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>320</x>
        <y>195</y>
        <z>300</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>260</x>
        <y>190</y>
        <z>300</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>290</x>
        <y>333</y>
        <z>229</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>284</x>
        <y>270</y>
        <z>197</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>237</x>
        <y>244</y>
        <z>225</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>340</x>
        <y>244</y>
        <z>225</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>287</x>
        <y>295</y>
        <z>175</z>
      </point>
      <point>
        <id>7</id>
        <specification>0</specification>
        <x>287</x>
        <y>275</y>
        <z>127</z>
      </point>
      <point>
        <id>8</id>
        <specification>0</specification>
        <x>288</x>
        <y>285</y>
        <z>113</z>
      </point>
      <point>
        <id>9</id>
        <specification>0</specification>
        <x>290</x>
        <y>291</y>
        <z>97</z>
      </point>
      <point>
        <id>10</id>
        <specification>0</specification>
        <x>293</x>
        <y>297</y>
        <z>79</z>
      </point>
      <point>
        <id>11</id>
        <specification>0</specification>
        <x>291</x>
        <y>308</y>
        <z>57</z>
      </point>
      <point>
        <id>12</id>
        <specification>0</specification>
        <x>305</x>
        <y>170</y>
        <z>215</z>
      </point>
      <point>
        <id>13</id>
        <specification>0</specification>
        <x>280</x>
        <y>170</y>
        <z>213</z>
      </point>
      <point>
        <id>14</id>
        <specification>0</specification>
        <x>105</x>
        <y>270</y>
        <z>35</z>
      </point>
      <point>
        <id>15</id>
        <specification>0</specification>
        <x>118</x>
        <y>285</y>
        <z>63</z>
      </point>
      <point>
        <id>16</id>
        <specification>0</specification>
        <x>257</x>
        <y>240</y>
        <z>45</z>
      </point>
      <point>
        <id>17</id>
        <specification>0</specification>
        <x>135</x>
        <y>297</y>
        <z>25</z>
      </point>
      <point>
        <id>18</id>
        <specification>0</specification>
        <x>194</x>
        <y>350</y>
        <z>40</z>
      </point>
      <point>
        <id>19</id>
        <specification>0</specification>
        <x>460</x>
        <y>295</y>
        <z>77</z>
      </point>
      <point>
        <id>20</id>
        <specification>0</specification>
        <x>389</x>
        <y>354</y>
        <z>40</z>
      </point>
      <point>
        <id>21</id>
        <specification>0</specification>
        <x>480</x>
        <y>280</y>
        <z>45</z>
      </point>
      <point>
        <id>22</id>
        <specification>0</specification>
        <x>444</x>
        <y>294</y>
        <z>37</z>
      </point>
      <point>
        <id>23</id>
        <specification>0</specification>
        <x>320</x>
        <y>240</y>
        <z>45</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>