# stub, automatically generated
SOFA_EXECUTABLE = "${SOFA_EXECUTABLE}"
HIFLOW_EXECUTABLE = "${HIFLOW_EXECUTABLE}"
ABAQUS_EXECUTABLE = "${ABAQUS_EXECUTABLE}"
FEBIO_EXECUTABLE = "${FEBIO_EXECUTABLE}"
FEBIO_POSTVIEW_EXECUTABLE = "${FEBIO_POSTVIEW_EXECUTABLE}"



MSML_DEFAULT_PACKAGE = "${CMAKE_CURRENT_SOURCE_DIR}/../share/"

MSML_ROOT= "${CMAKE_CURRENT_SOURCE_DIR}/../src"
